FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development \
    PATH=/app/node_modules/.bin:$PATH

COPY package*.json tsconfig.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
